# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paint.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_paint(object):
    def setupUi(self, paint):
        paint.setObjectName("paint")
        paint.resize(328, 692)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(paint.sizePolicy().hasHeightForWidth())
        paint.setSizePolicy(sizePolicy)

        self.retranslateUi(paint)
        QtCore.QMetaObject.connectSlotsByName(paint)

    def retranslateUi(self, paint):
        _translate = QtCore.QCoreApplication.translate
        paint.setWindowTitle(_translate("paint", "Form"))
