# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rf(object):
    def setupUi(self, rf):
        rf.setObjectName("rf")
        rf.resize(175, 299)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(rf.sizePolicy().hasHeightForWidth())
        rf.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(rf)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(rf)
        self.groupBox.setStyleSheet("background-color: rgb(255, 216, 171);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_ant0 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ant0.sizePolicy().hasHeightForWidth())
        self.pushButton_ant0.setSizePolicy(sizePolicy)
        self.pushButton_ant0.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_ant0.setObjectName("pushButton_ant0")
        self.verticalLayout.addWidget(self.pushButton_ant0)
        self.pushButton_ant1 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ant1.sizePolicy().hasHeightForWidth())
        self.pushButton_ant1.setSizePolicy(sizePolicy)
        self.pushButton_ant1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_ant1.setObjectName("pushButton_ant1")
        self.verticalLayout.addWidget(self.pushButton_ant1)
        self.pushButton_ant2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ant2.sizePolicy().hasHeightForWidth())
        self.pushButton_ant2.setSizePolicy(sizePolicy)
        self.pushButton_ant2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_ant2.setObjectName("pushButton_ant2")
        self.verticalLayout.addWidget(self.pushButton_ant2)
        self.pushButton_ant3 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ant3.sizePolicy().hasHeightForWidth())
        self.pushButton_ant3.setSizePolicy(sizePolicy)
        self.pushButton_ant3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_ant3.setObjectName("pushButton_ant3")
        self.verticalLayout.addWidget(self.pushButton_ant3)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(rf)
        QtCore.QMetaObject.connectSlotsByName(rf)

    def retranslateUi(self, rf):
        _translate = QtCore.QCoreApplication.translate
        rf.setWindowTitle(_translate("rf", "Form"))
        self.pushButton_ant0.setText(_translate("rf", "ANT 0"))
        self.pushButton_ant1.setText(_translate("rf", "ANT 1"))
        self.pushButton_ant2.setText(_translate("rf", "ANT 2"))
        self.pushButton_ant3.setText(_translate("rf", "ANT 3"))
